// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwqmspzjibtbdjpqicpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cW1zcHpqaWJ0YmRqcHFpY3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDgyMTQsImV4cCI6MjA2Mjk4NDIxNH0.M_ShyRjasbDUUoK2t2FIsTSzaZNuVsIwsCuPN2mzGSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);